name: strategy test

on: 
  workflow_dispatch:

jobs:
  loop_job:
    runs-on: windows-latest
    steps:
      - name: Set Environment Variable
        run: |
          $env:MY_ARRAY = '[{"BATCL00101": "./HybridCapOh/HybridCapOh.Batch/Claim/BATCL00101.AccountTransferDataCreate/BATCL00101.AccountTransferDataCreate.csproj"}, {"BATCL00102": "./HybridCapOh/HybridCapOh.Batch/Claim/BATCL00201.AccountTransferResultDataImport/BATCL00201.AccountTransferResultDataImport.csproj"}]'
          $array = $env:MY_ARRAY | ConvertFrom-Json
          foreach ($item in $array) {
            Write-Output "Loop iteration: $($item.Keys)"
            # ここにループ内で実行したいコマンドを追加
          }
