name: strategy test

on: 
  workflow_dispatch:

env:
  MY_JSON_CONFIG: '{"key1": "value1", "key2": "value2"}'
  
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["{\"name\": \"ubuntu-latest\"}", "{\"name\": \"windows-latest\"}"]
        version: [10, 12, 14]
    steps:
      - name: Show Matrix Values
        run: |
          echo "OS: ${{ fromJson(matrix.os).name }}"
          echo "Version: ${{ matrix.version }}"
