name: strategy test

on: 
  workflow_dispatch:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10, 12, 14]
        
    steps:
      - name: Echo Message
        run: echo "Hello from ${{ matrix.os }} with Node.js version ${{ matrix.version }}"
