name: strategy test

on: 
  workflow_dispatch:

env:
  FRUIT: '["Apple", "Pear", "Banana", "Orange"]'

jobs:
  execute_jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        FRUIT: ${{ fromJson(env.FRUIT) }}
    steps:
      - name: Show Fruit
        run: |
          echo "Fruit: ${{ matrix.FRUIT }}"
