name: strategy test

on: 
  workflow_dispatch:

jobs:
  loop_job:
    runs-on: windows-latest
    steps:
      - name: Run Loop Script
        run: |
          $env:MY_ARRAY = "apple", "banana", "orange" # ここに配列の要素を定義
          foreach ($item in $env:MY_ARRAY) {
            Write-Output "Loop iteration: $item"
            # ここにループ内で実行したいコマンドを追加
          }
